const accountNames = [
  "round7bb",
  "JD HCIM",
  "Proovoomly",
  "Iron or Lead",
  "Plan too Die",
  "pvp fenny",
  "c haws",
  "jd hcim",
  "sub2jala pvp",
  "20m edamura",
  "Okay Woman",
  "realdmm",
  "One Lil Life",
  "PVP HCIM AMS",
  "Shom HC I",
  "hc wobblybob",
  "NotHCPromise",
  "dontafkidiot",
  "hc ditzy",
  "pvp ls",
  "hc horrorpvp",
  "pvp conner",
  "finn pvp hc",
  "SeqenenTrash",
  "Diablo Fenix",
  "Aframax",
  "Non Pvp Only",
  "Scry my ass",
  "HC PvP MCFS",
  "PVP Koen",
  "GodSpeed PVP",
  "PVP Verf",
  "hm for off",
  "pivipi",
  "mich xanov",
  "hc moonpie",
  "lron samurai",
  "No Fixed Bae",
  "PvP Escape",
  "hc pvp zach",
  "llama again",
  "tigers ass",
  "panicteles",
  "strangecore",
  "just1a2bot3",
  "4th att3mpt",
  "hcbeanflicka",
  "notpvp kimmo",
  "pvp jeffpoe",
  "rip thejacob",
  "baked granny",
  "justapvphc",
];

export default accountNames;
